// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: staticaddr.proto

// We can't change this to swapserverrpc, it would be a breaking change because
// the package name is also contained in the HTTP URIs and old clients would
// call the wrong endpoints. Luckily with the go_package option we can have
// different golang and RPC package names to fix protobuf namespace conflicts.

package swapserverrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StaticAddressServer_ServerNewAddress_FullMethodName               = "/looprpc.StaticAddressServer/ServerNewAddress"
	StaticAddressServer_ServerWithdrawDeposits_FullMethodName         = "/looprpc.StaticAddressServer/ServerWithdrawDeposits"
	StaticAddressServer_ServerPsbtWithdrawDeposits_FullMethodName     = "/looprpc.StaticAddressServer/ServerPsbtWithdrawDeposits"
	StaticAddressServer_ServerStaticAddressLoopIn_FullMethodName      = "/looprpc.StaticAddressServer/ServerStaticAddressLoopIn"
	StaticAddressServer_PushStaticAddressHtlcSigs_FullMethodName      = "/looprpc.StaticAddressServer/PushStaticAddressHtlcSigs"
	StaticAddressServer_PushStaticAddressSweeplessSigs_FullMethodName = "/looprpc.StaticAddressServer/PushStaticAddressSweeplessSigs"
)

// StaticAddressServerClient is the client API for StaticAddressServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StaticAddressServerClient interface {
	// ServerNewAddress generates a new static address for the client to use.
	// The server will generate the address and return the server key and the
	// address's CSV expiry.
	ServerNewAddress(ctx context.Context, in *ServerNewAddressRequest, opts ...grpc.CallOption) (*ServerNewAddressResponse, error)
	// Deprecated: Do not use.
	// ServerWithdrawDeposits allows to cooperatively sweep deposits that
	// haven't timed out yet to the client's wallet. The server will generate
	// the partial sigs for the client's selected deposits.
	//
	// Deprecated: use ServerPsbtWithdrawDeposits instead.
	ServerWithdrawDeposits(ctx context.Context, in *ServerWithdrawRequest, opts ...grpc.CallOption) (*ServerWithdrawResponse, error)
	// ServerPsbtWithdrawDeposits allows to cooperatively sweep deposits that
	// haven't timed out yet to the client's wallet. In contrast to
	// ServerWithdrawDeposits which provides the paramters to form the
	// withdrawal transaction, this service method will provide a psbt which
	// is signed by the server.
	ServerPsbtWithdrawDeposits(ctx context.Context, in *ServerPsbtWithdrawRequest, opts ...grpc.CallOption) (*ServerPsbtWithdrawResponse, error)
	// ServerStaticAddressLoopIn initiates a static address loop-in swap. The
	// server will respond with htlc details that the client can use to
	// construct and sign the htlc tx.
	ServerStaticAddressLoopIn(ctx context.Context, in *ServerStaticAddressLoopInRequest, opts ...grpc.CallOption) (*ServerStaticAddressLoopInResponse, error)
	// PushStaticAddressHtlcSigs pushes the client's htlc tx sigs to the server.
	PushStaticAddressHtlcSigs(ctx context.Context, in *PushStaticAddressHtlcSigsRequest, opts ...grpc.CallOption) (*PushStaticAddressHtlcSigsResponse, error)
	// PushStaticAddressSweeplessSigs pushes the client's sweepless sweep tx
	// sigs to the server.
	PushStaticAddressSweeplessSigs(ctx context.Context, in *PushStaticAddressSweeplessSigsRequest, opts ...grpc.CallOption) (*PushStaticAddressSweeplessSigsResponse, error)
}

type staticAddressServerClient struct {
	cc grpc.ClientConnInterface
}

func NewStaticAddressServerClient(cc grpc.ClientConnInterface) StaticAddressServerClient {
	return &staticAddressServerClient{cc}
}

func (c *staticAddressServerClient) ServerNewAddress(ctx context.Context, in *ServerNewAddressRequest, opts ...grpc.CallOption) (*ServerNewAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerNewAddressResponse)
	err := c.cc.Invoke(ctx, StaticAddressServer_ServerNewAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *staticAddressServerClient) ServerWithdrawDeposits(ctx context.Context, in *ServerWithdrawRequest, opts ...grpc.CallOption) (*ServerWithdrawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerWithdrawResponse)
	err := c.cc.Invoke(ctx, StaticAddressServer_ServerWithdrawDeposits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticAddressServerClient) ServerPsbtWithdrawDeposits(ctx context.Context, in *ServerPsbtWithdrawRequest, opts ...grpc.CallOption) (*ServerPsbtWithdrawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerPsbtWithdrawResponse)
	err := c.cc.Invoke(ctx, StaticAddressServer_ServerPsbtWithdrawDeposits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticAddressServerClient) ServerStaticAddressLoopIn(ctx context.Context, in *ServerStaticAddressLoopInRequest, opts ...grpc.CallOption) (*ServerStaticAddressLoopInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerStaticAddressLoopInResponse)
	err := c.cc.Invoke(ctx, StaticAddressServer_ServerStaticAddressLoopIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticAddressServerClient) PushStaticAddressHtlcSigs(ctx context.Context, in *PushStaticAddressHtlcSigsRequest, opts ...grpc.CallOption) (*PushStaticAddressHtlcSigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushStaticAddressHtlcSigsResponse)
	err := c.cc.Invoke(ctx, StaticAddressServer_PushStaticAddressHtlcSigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticAddressServerClient) PushStaticAddressSweeplessSigs(ctx context.Context, in *PushStaticAddressSweeplessSigsRequest, opts ...grpc.CallOption) (*PushStaticAddressSweeplessSigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushStaticAddressSweeplessSigsResponse)
	err := c.cc.Invoke(ctx, StaticAddressServer_PushStaticAddressSweeplessSigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaticAddressServerServer is the server API for StaticAddressServer service.
// All implementations must embed UnimplementedStaticAddressServerServer
// for forward compatibility.
type StaticAddressServerServer interface {
	// ServerNewAddress generates a new static address for the client to use.
	// The server will generate the address and return the server key and the
	// address's CSV expiry.
	ServerNewAddress(context.Context, *ServerNewAddressRequest) (*ServerNewAddressResponse, error)
	// Deprecated: Do not use.
	// ServerWithdrawDeposits allows to cooperatively sweep deposits that
	// haven't timed out yet to the client's wallet. The server will generate
	// the partial sigs for the client's selected deposits.
	//
	// Deprecated: use ServerPsbtWithdrawDeposits instead.
	ServerWithdrawDeposits(context.Context, *ServerWithdrawRequest) (*ServerWithdrawResponse, error)
	// ServerPsbtWithdrawDeposits allows to cooperatively sweep deposits that
	// haven't timed out yet to the client's wallet. In contrast to
	// ServerWithdrawDeposits which provides the paramters to form the
	// withdrawal transaction, this service method will provide a psbt which
	// is signed by the server.
	ServerPsbtWithdrawDeposits(context.Context, *ServerPsbtWithdrawRequest) (*ServerPsbtWithdrawResponse, error)
	// ServerStaticAddressLoopIn initiates a static address loop-in swap. The
	// server will respond with htlc details that the client can use to
	// construct and sign the htlc tx.
	ServerStaticAddressLoopIn(context.Context, *ServerStaticAddressLoopInRequest) (*ServerStaticAddressLoopInResponse, error)
	// PushStaticAddressHtlcSigs pushes the client's htlc tx sigs to the server.
	PushStaticAddressHtlcSigs(context.Context, *PushStaticAddressHtlcSigsRequest) (*PushStaticAddressHtlcSigsResponse, error)
	// PushStaticAddressSweeplessSigs pushes the client's sweepless sweep tx
	// sigs to the server.
	PushStaticAddressSweeplessSigs(context.Context, *PushStaticAddressSweeplessSigsRequest) (*PushStaticAddressSweeplessSigsResponse, error)
	mustEmbedUnimplementedStaticAddressServerServer()
}

// UnimplementedStaticAddressServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStaticAddressServerServer struct{}

func (UnimplementedStaticAddressServerServer) ServerNewAddress(context.Context, *ServerNewAddressRequest) (*ServerNewAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerNewAddress not implemented")
}
func (UnimplementedStaticAddressServerServer) ServerWithdrawDeposits(context.Context, *ServerWithdrawRequest) (*ServerWithdrawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerWithdrawDeposits not implemented")
}
func (UnimplementedStaticAddressServerServer) ServerPsbtWithdrawDeposits(context.Context, *ServerPsbtWithdrawRequest) (*ServerPsbtWithdrawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerPsbtWithdrawDeposits not implemented")
}
func (UnimplementedStaticAddressServerServer) ServerStaticAddressLoopIn(context.Context, *ServerStaticAddressLoopInRequest) (*ServerStaticAddressLoopInResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerStaticAddressLoopIn not implemented")
}
func (UnimplementedStaticAddressServerServer) PushStaticAddressHtlcSigs(context.Context, *PushStaticAddressHtlcSigsRequest) (*PushStaticAddressHtlcSigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushStaticAddressHtlcSigs not implemented")
}
func (UnimplementedStaticAddressServerServer) PushStaticAddressSweeplessSigs(context.Context, *PushStaticAddressSweeplessSigsRequest) (*PushStaticAddressSweeplessSigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushStaticAddressSweeplessSigs not implemented")
}
func (UnimplementedStaticAddressServerServer) mustEmbedUnimplementedStaticAddressServerServer() {}
func (UnimplementedStaticAddressServerServer) testEmbeddedByValue()                             {}

// UnsafeStaticAddressServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StaticAddressServerServer will
// result in compilation errors.
type UnsafeStaticAddressServerServer interface {
	mustEmbedUnimplementedStaticAddressServerServer()
}

func RegisterStaticAddressServerServer(s grpc.ServiceRegistrar, srv StaticAddressServerServer) {
	// If the following call panics, it indicates UnimplementedStaticAddressServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StaticAddressServer_ServiceDesc, srv)
}

func _StaticAddressServer_ServerNewAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerNewAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticAddressServerServer).ServerNewAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaticAddressServer_ServerNewAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticAddressServerServer).ServerNewAddress(ctx, req.(*ServerNewAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaticAddressServer_ServerWithdrawDeposits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerWithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticAddressServerServer).ServerWithdrawDeposits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaticAddressServer_ServerWithdrawDeposits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticAddressServerServer).ServerWithdrawDeposits(ctx, req.(*ServerWithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaticAddressServer_ServerPsbtWithdrawDeposits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerPsbtWithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticAddressServerServer).ServerPsbtWithdrawDeposits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaticAddressServer_ServerPsbtWithdrawDeposits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticAddressServerServer).ServerPsbtWithdrawDeposits(ctx, req.(*ServerPsbtWithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaticAddressServer_ServerStaticAddressLoopIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerStaticAddressLoopInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticAddressServerServer).ServerStaticAddressLoopIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaticAddressServer_ServerStaticAddressLoopIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticAddressServerServer).ServerStaticAddressLoopIn(ctx, req.(*ServerStaticAddressLoopInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaticAddressServer_PushStaticAddressHtlcSigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushStaticAddressHtlcSigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticAddressServerServer).PushStaticAddressHtlcSigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaticAddressServer_PushStaticAddressHtlcSigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticAddressServerServer).PushStaticAddressHtlcSigs(ctx, req.(*PushStaticAddressHtlcSigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaticAddressServer_PushStaticAddressSweeplessSigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushStaticAddressSweeplessSigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticAddressServerServer).PushStaticAddressSweeplessSigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaticAddressServer_PushStaticAddressSweeplessSigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticAddressServerServer).PushStaticAddressSweeplessSigs(ctx, req.(*PushStaticAddressSweeplessSigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StaticAddressServer_ServiceDesc is the grpc.ServiceDesc for StaticAddressServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StaticAddressServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "looprpc.StaticAddressServer",
	HandlerType: (*StaticAddressServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerNewAddress",
			Handler:    _StaticAddressServer_ServerNewAddress_Handler,
		},
		{
			MethodName: "ServerWithdrawDeposits",
			Handler:    _StaticAddressServer_ServerWithdrawDeposits_Handler,
		},
		{
			MethodName: "ServerPsbtWithdrawDeposits",
			Handler:    _StaticAddressServer_ServerPsbtWithdrawDeposits_Handler,
		},
		{
			MethodName: "ServerStaticAddressLoopIn",
			Handler:    _StaticAddressServer_ServerStaticAddressLoopIn_Handler,
		},
		{
			MethodName: "PushStaticAddressHtlcSigs",
			Handler:    _StaticAddressServer_PushStaticAddressHtlcSigs_Handler,
		},
		{
			MethodName: "PushStaticAddressSweeplessSigs",
			Handler:    _StaticAddressServer_PushStaticAddressSweeplessSigs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "staticaddr.proto",
}
